image: maven:3.6.1

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn -B test package
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - docker build -t pcandido/avaliacao .
          - docker push pcandido/avaliacao
        services:
          - docker